# Generated by Django 6.0.3 on 2026-03-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_flashcard_ease_factor_flashcard_interval_days_and_more'),
        ('planner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='studysession',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='library.resource'),
        ),
    ]
