# Generated by Django 6.0.3 on 2026-03-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('planner', '0003_add_resource_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='assignments.assignment'),
        ),
    ]
