# Generated by Django 6.0.3 on 2026-03-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspacedocument',
            options={'ordering': ['-is_pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='workspacedocument',
            name='content_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('rich', 'Rich Text')], default='markdown', max_length=20),
        ),
        migrations.AddField(
            model_name='workspacedocument',
            name='emoji',
            field=models.CharField(default='📄', max_length=10),
        ),
        migrations.AddField(
            model_name='workspacedocument',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacedocument',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
