# Generated by Django 6.0.3 on 2026-04-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacetask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
