'use client'
import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { ArrowRight, Plus, X } from 'lucide-react'
import { learningApi } from '@/lib/api'
import FirstJourneyBuilder from '@/components/journey-builder/FirstJourneyBuilder'
import FlowCompanion, { type FlowCompanionState } from '@/components/onboarding/FlowCompanion'
import FlowLoader from '@/components/ui/FlowLoader'
import { normalizeReadableMath } from '@/lib/mathFormatting'

export default function JourneyHubPage() {
  const qc = useQueryClient()
  const params = useSearchParams(); const initialSource = Number(params.get('source') || 0); const [creating, setCreating] = useState(params.get('create') === '1' || Boolean(initialSource)); const [flowState, setFlowState] = useState<FlowCompanionState>('idle')
  const pathsQuery = useQuery({ queryKey: ['learning-paths'], queryFn: () => learningApi.getPaths().then(r => Array.isArray(r.data) ? r.data : r.data?.results || []) })
  const activate = useMutation({ mutationFn: (id: string) => learningApi.setActivePath(id), onSuccess: () => qc.invalidateQueries({ queryKey: ['learning-paths'] }) })
  const paths = useMemo(() => pathsQuery.data || [], [pathsQuery.data]); const active = useMemo(() => paths.find((p: any) => p.status === 'active') || paths.find((p: any) => p.status !== 'completed'), [paths]); const others = paths.filter((p: any) => p.id !== active?.id && p.status !== 'completed'); const completed = paths.filter((p: any) => p.status === 'completed')
  const detailQuery = useQuery({ queryKey: ['learning-path', active?.id], queryFn: () => learningApi.getPath(active.id).then(r => r.data), enabled: Boolean(active?.id) })
  const current = detailQuery.data?.concepts?.find((item: any) => item.status === 'current'); const sessionQuery = useQuery({ queryKey: ['teaching-session', current?.id], queryFn: () => learningApi.getTeachingSession(current.id).then(r => r.data), enabled: Boolean(current?.id), retry: false }); const open = sessionQuery.data && !['completed','not_started'].includes(sessionQuery.data.status)
  if (pathsQuery.isLoading) return <FlowLoader state="thinking" message="Finding your spot." className="min-h-[80dvh]" />
  return <main className="flow-v2 flow-atmosphere min-h-[calc(100dvh-4rem)] px-5 py-9 md:px-10 lg:px-14"><div className="mx-auto max-w-[88rem]"><header className="flex items-end justify-between gap-5"><div><p className="flow-eyebrow">Journey</p><h1 className="mt-2 text-[clamp(3rem,7vw,6rem)] font-black leading-none tracking-[-.06em]">Where you’re going.</h1></div><button onClick={() => setCreating(true)} className="inline-flex min-h-12 items-center gap-2 bg-flow-orange px-5 font-black text-flow-void"><Plus /> New Journey</button></header>{active ? <section className="relative mt-12 overflow-hidden border-y border-white/10 py-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_30%,rgba(148,124,255,.18),transparent_35rem)]" /><div className="relative grid gap-10 lg:grid-cols-[minmax(0,1fr)_24rem] lg:items-center"><div><p className="flow-eyebrow">Current Journey</p><h2 className="mt-3 text-[clamp(2.5rem,6vw,5.5rem)] font-black leading-[.95] tracking-[-.055em]">{active.title}</h2><p className="mt-4 max-w-2xl text-lg text-flow-muted">{active.goal || active.description}</p><div className="mt-8 flex h-16 max-w-2xl items-center gap-2" aria-label={`${active.mastery_percent}% complete`}><span className="h-4 w-4 rounded-full bg-flow-success" /><span className="h-1 flex-1 bg-gradient-to-r from-flow-success via-flow-orange to-white/10" /><span className="h-9 w-9 rotate-6 bg-flow-orange shadow-[0_0_28px_rgba(255,122,26,.5)]" style={{ marginLeft: `-${Math.max(2, 100 - active.mastery_percent)}%` }} /></div><div className="mt-6 flex flex-wrap items-center gap-5"><Link href={`/learn/${active.id}${open ? `?concept=${current.id}` : ''}`} className="inline-flex min-h-14 items-center gap-2 bg-flow-orange px-7 font-black text-flow-void shadow-[0_6px_0_#8f3600]">{open ? 'Continue with Flow' : 'Continue Journey'} <ArrowRight /></Link><span className="font-bold text-flow-muted">{active.concepts_completed}/{active.total_concepts} concepts · {active.due_reviews || 0} due</span></div></div><div><FlowCompanion state={open ? 'teaching' : 'idle'} className="mx-auto w-56" /><p className="text-center text-sm font-bold text-flow-muted">{open ? `${sessionQuery.data.completion_evaluation?.objectives_satisfied || 0}/${sessionQuery.data.completion_evaluation?.objectives_total || 0} objectives in ${normalizeReadableMath(current?.title || '')}` : current ? `Next: ${normalizeReadableMath(current.title)}` : 'Your route is complete.'}</p></div></div></section> : <section className="mt-14 grid items-center gap-8 lg:grid-cols-[1fr_24rem]"><div><h2 className="text-4xl font-black">No Journey yet.</h2><p className="mt-3 text-flow-muted">Bring a Source and Flow will turn it into a route.</p><button onClick={() => setCreating(true)} className="mt-6 bg-flow-orange px-6 py-4 font-black text-flow-void">Create a Journey</button></div><FlowCompanion state="encouraging" /></section>}
  {others.length > 0 && <section className="mt-14"><p className="flow-eyebrow">Other Journeys</p><div className="mt-5 divide-y divide-white/10 border-y border-white/10">{others.map((path: any) => <div key={path.id} className="group grid gap-4 py-6 sm:grid-cols-[1fr_auto] sm:items-center"><Link href={`/learn/${path.id}`}><h3 className="text-2xl font-black group-hover:text-flow-orange">{path.title}</h3><p className="mt-1 text-sm text-flow-muted">{path.subject || path.goal}</p></Link><div className="flex items-center gap-4"><span className="font-black text-flow-violet">{path.mastery_percent}%</span><button disabled={activate.isPending} onClick={() => activate.mutate(path.id)} className="text-xs font-black text-flow-orange">Make current</button><Link href={`/learn/${path.id}`} className="font-black">Open →</Link></div></div>)}</div></section>}{completed.length > 0 && <details className="mt-12 border-t border-white/10 pt-6"><summary className="cursor-pointer font-black text-flow-muted">Completed Journeys ({completed.length})</summary><div className="mt-4 space-y-3">{completed.map((path: any) => <Link key={path.id} href={`/learn/${path.id}`} className="block text-sm font-bold text-flow-muted hover:text-flow-ink">{path.title} · {path.total_xp} XP</Link>)}</div></details>}</div>
  {creating && <div className="fixed inset-0 z-[70] overflow-y-auto bg-flow-void/98 p-5 pb-20 text-flow-ink md:p-12"><button onClick={() => setCreating(false)} aria-label="Close Journey builder" className="fixed right-5 top-5 z-10 grid h-12 w-12 place-items-center bg-flow-raised"><X /></button><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[minmax(0,1fr)_22rem]"><FirstJourneyBuilder initialResourceIds={initialSource ? [initialSource] : []} onPersist={async () => true} onFlowState={setFlowState} /><aside className="hidden lg:block"><FlowCompanion state={flowState} className="sticky top-12 w-full" /></aside></div></div>}
  </main>
}
