'use client'
import { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import { ArrowDown, Check, ChevronDown, ChevronUp, Lightbulb } from 'lucide-react'
import type { EncounterActivity } from '@/types/journey'
import { normalizeForRendering, normalizeReadableMath } from '@/lib/mathFormatting'

export default function JourneyLearningObject({ object }: { object: EncounterActivity }) {
  if (['concept','key_idea'].includes(object.type)) return <Concept object={object} />
  if (['process','sequence'].includes(object.type)) return <Process object={object} />
  if (object.type === 'cause_effect') return <Chain object={object} />
  if (object.type === 'comparison') return <Comparison object={object} />
  if (object.type === 'formula') return <Formula object={object} />
  if (object.type === 'worked_example') return <Worked object={object} />
  if (object.type === 'diagram') return <Diagram object={object} />
  return <Example object={object} />
}
const Eye = ({ children }: { children: string }) => <p className="text-[10px] font-black uppercase tracking-[.18em] text-flow-orange">{children}</p>
const Copy = ({ children }: { children: string }) => <div className="prose prose-invert prose-sm mt-3 max-w-none text-flow-muted prose-strong:text-flow-ink"><ReactMarkdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>{normalizeForRendering(children || '')}</ReactMarkdown></div>
const title = (o: EncounterActivity) => normalizeReadableMath(o.title || o.prompt)
const strings = (v: unknown) => Array.isArray(v) ? v.map(x => typeof x === 'string' ? x : String((x as any)?.body || (x as any)?.label || '')).filter(Boolean) : []

function Concept({ object }: { object: EncounterActivity }) { return <section className="border-l-4 border-flow-orange py-2 pl-4 sm:pl-6"><Eye>{object.type === 'key_idea' ? 'Key idea' : 'Concept'}</Eye><h3 className="mt-2 text-xl font-black leading-snug sm:text-2xl">{title(object)}</h3><Copy>{object.content?.body || object.content?.key_idea || object.content?.takeaway || ''}</Copy>{object.content?.takeaway && <p className="mt-4 flex gap-2 text-sm font-bold"><Lightbulb className="h-4 w-4 shrink-0 text-flow-violet" />{normalizeReadableMath(object.content.takeaway)}</p>}</section> }
function Process({ object }: { object: EncounterActivity }) { const steps = strings(object.content?.steps); return <section><Eye>{object.type === 'sequence' ? 'Sequence' : 'Process'}</Eye><h3 className="mt-2 text-xl font-black">{title(object)}</h3><ol className="mt-5 grid gap-0 sm:grid-cols-[repeat(auto-fit,minmax(9rem,1fr))]">{steps.map((step,index)=><li key={index} className="relative flex gap-3 pb-7 sm:block sm:pr-7"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-flow-orange font-black text-flow-void">{index+1}</span><p className="pt-1 text-sm font-bold leading-6 sm:mt-3 sm:pt-0">{normalizeReadableMath(step)}</p>{index<steps.length-1&&<ArrowDown className="absolute bottom-1 left-2 h-4 w-4 text-flow-violet sm:-right-0 sm:left-auto sm:top-2 sm:-rotate-90" />}</li>)}</ol></section> }
function Chain({ object }: { object: EncounterActivity }) { const steps=strings(object.content?.steps); return <section><Eye>Cause → effect</Eye><h3 className="mt-2 text-xl font-black">{title(object)}</h3><div className="mt-5">{steps.map((step,index)=><div key={index}><div className="border-l-2 border-flow-violet bg-flow-violet/5 px-4 py-3 text-sm font-bold">{normalizeReadableMath(step)}</div>{index<steps.length-1&&<ArrowDown className="mx-auto my-2 h-4 w-4 text-flow-orange" />}</div>)}</div></section> }
function Comparison({ object }: { object: EncounterActivity }) { const columns=object.content?.columns||[]; const rows=object.content?.rows||[]; return <section><Eye>Compare</Eye><h3 className="mt-2 text-xl font-black">{title(object)}</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{columns.slice(0,2).map((column,i)=><article key={column} className="border-t-4 border-flow-violet bg-white/[.035] p-4"><h4 className="font-black">{normalizeReadableMath(column)}</h4><ul className="mt-3 space-y-2 text-sm text-flow-muted">{rows.map((row,j)=><li key={j}>{normalizeReadableMath(row[i]||'')}</li>)}</ul></article>)}</div></section> }
function Formula({ object }: { object: EncounterActivity }) { return <section><Eye>Formula</Eye><h3 className="mt-2 text-xl font-black">{title(object)}</h3><div className="mt-5 overflow-x-auto border-y border-white/10 py-4 text-center text-xl"><Copy>{`$$${object.content?.formula||object.content?.takeaway||''}$$`}</Copy></div>{object.content?.parts?.length?<dl className="mt-4 grid gap-3 sm:grid-cols-2">{object.content.parts.map((part,i)=><div key={i} className="flex gap-3"><dt className="font-mono font-black text-flow-violet">{part.symbol}</dt><dd className="text-sm text-flow-muted">{part.meaning}</dd></div>)}</dl>:null}</section> }
function Worked({ object }: { object: EncounterActivity }) { const [shown,setShown]=useState(1); const steps=Array.isArray(object.content?.steps)?object.content!.steps!.map((x:any,i)=>typeof x==='string'?{label:`Step ${i+1}`,body:x}:{label:x.label||`Step ${i+1}`,body:x.body}).filter(x=>x.body):[]; if(!steps.length)return <Example object={object}/>; return <section><Eye>Worked example</Eye><h3 className="mt-2 text-xl font-black">{title(object)}</h3><ol className="mt-5 space-y-3">{steps.map((step,i)=><li key={i} className="border-l-2 border-white/15 pl-4"><p className="text-xs font-black uppercase text-flow-violet">{step.label}</p>{i<shown?<Copy>{step.body}</Copy>:<button onClick={()=>setShown(i+1)} className="mt-2 min-h-11 text-sm font-black text-flow-orange focus-visible:ring-2">Reveal step {i+1}</button>}</li>)}</ol></section> }
function Diagram({ object }: { object: EncounterActivity }) { const nodes=object.content?.nodes||[]; return <section><Eye>How it connects</Eye><h3 className="mt-2 text-xl font-black">{title(object)}</h3><div className="mt-5 flex flex-col items-center">{nodes.map((node,i)=><div key={node.id||i} className="contents"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3 text-center text-sm font-bold">{normalizeReadableMath(node.label)}</div>{i<nodes.length-1&&<ArrowDown className="my-2 h-5 w-5 text-flow-orange" />}</div>)}</div></section> }
function Example({ object }: { object: EncounterActivity }) { return <section className="border-l-4 border-flow-violet pl-4 sm:pl-6"><Eye>{object.type==='example'?'Example':'Learning object'}</Eye><h3 className="mt-2 text-xl font-black">{title(object)}</h3>{object.content?.lead&&<p className="mt-3 text-sm font-bold text-flow-muted">{object.content.lead}</p>}<Copy>{object.content?.example||object.content?.body||object.content?.takeaway||object.prompt}</Copy></section> }

export function CollapsedPractice({ activity }: { activity: EncounterActivity }) { const [open,setOpen]=useState(false); return <section className="border-l-2 border-flow-success/60 py-2 pl-4"><button onClick={()=>setOpen(v=>!v)} aria-expanded={open} className="flex min-h-11 w-full items-center gap-3 text-left focus-visible:ring-2 focus-visible:ring-flow-orange"><Check className="h-4 w-4 text-flow-success"/><span className="flex-1"><span className="block text-[10px] font-black uppercase tracking-[.16em] text-flow-success">Completed check</span><span className="line-clamp-1 text-sm font-bold">{normalizeReadableMath(activity.prompt)}</span></span>{open?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{open&&<p className="mt-2 pl-7 text-sm text-flow-muted">Historical activity · read only. Your evidence remains saved.</p>}</section> }
