'use client'
import { useState } from 'react'
import { motion } from 'framer-motion'
import ReactMarkdown from 'react-markdown'
import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import { ArrowDown, ArrowRight, Check, ChevronDown, ChevronUp, Lightbulb, Sparkles } from 'lucide-react'
import type { EncounterActivity } from '@/types/journey'
import { normalizeForRendering, normalizeReadableMath } from '@/lib/mathFormatting'
import { ArchitectureCanvas, CycleCanvas, EvidenceCanvas, GraphCanvas, LabeledDiagramCanvas } from '@/components/journey-world/TeachingCanvas'

export default function JourneyLearningObject({ object }: { object: EncounterActivity }) {
  if (object.content?.knowledge_type === 'CYCLE') return <CycleCanvas object={object}/>
  if (object.type === 'architecture') return <ArchitectureCanvas object={object}/>
  if (object.type === 'evidence_highlight') return <EvidenceCanvas object={object}/>
  if (object.type === 'simple_graph') return <GraphCanvas object={object}/>
  if (object.type === 'labeled_diagram') return <LabeledDiagramCanvas object={object}/>
  if (['process','sequence','cause_effect'].includes(object.type)) return <FlowPath object={object}/>
  if (['relationship','diagram'].includes(object.type)) return <RelationshipMap object={object}/>
  if (object.type === 'comparison') return <Comparison object={object}/>
  if (object.type === 'formula') return <Formula object={object}/>
  if (object.type === 'worked_example') return <Worked object={object}/>
  if (object.type === 'example') return <Example object={object}/>
  return <Idea object={object}/>
}
const title=(o:EncounterActivity)=>normalizeReadableMath(o.title||o.prompt)
const strings=(v:unknown)=>Array.isArray(v)?v.map(x=>typeof x==='string'?x:String((x as any)?.body||(x as any)?.label||'')).filter(Boolean):[]
const Copy=({children,className=''}:{children:string;className?:string})=><div className={`prose prose-invert prose-sm max-w-none text-flow-muted prose-p:leading-7 prose-strong:text-flow-ink ${className}`}><ReactMarkdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>{normalizeForRendering(children||'')}</ReactMarkdown></div>
function Idea({object}:{object:EncounterActivity}){const body=object.content?.body||object.content?.key_idea||object.content?.takeaway||'';return <section className="mx-auto max-w-2xl py-2 text-center"><motion.div initial={{scale:.8,opacity:0}} animate={{scale:1,opacity:1}} className="mx-auto grid h-10 w-10 place-items-center rounded-2xl bg-flow-orange/15 text-flow-orange"><Lightbulb className="h-5 w-5"/></motion.div><h3 className="mt-4 text-[clamp(1.3rem,2.6vw,2rem)] font-black leading-tight tracking-[-.035em]">{title(object)}</h3><Copy className="mx-auto mt-3 max-w-xl text-left sm:text-center">{body}</Copy></section>}
function FlowPath({object}:{object:EncounterActivity}){const steps=strings(object.content?.steps);return <section className="mx-auto max-w-4xl"><h3 className="text-center text-[clamp(1.25rem,2.5vw,1.8rem)] font-black">{title(object)}</h3><div className="mt-7 flex flex-col items-center justify-center gap-2 md:flex-row md:gap-0">{steps.map((step,i)=><div key={i} className="contents"><motion.div initial={{opacity:0,scale:.82,y:12}} animate={{opacity:1,scale:1,y:0}} transition={{delay:i*.18,duration:.32}} className="relative grid min-h-24 w-full max-w-52 place-items-center rounded-[1.6rem] border border-white/10 bg-gradient-to-br from-white/[.07] to-white/[.025] p-4 text-center text-sm font-black leading-5 shadow-[0_16px_45px_rgba(0,0,0,.18)]"><span className="absolute -top-2.5 grid h-6 min-w-6 place-items-center rounded-full bg-flow-orange px-1.5 text-[10px] text-flow-void">{i+1}</span>{normalizeReadableMath(step)}</motion.div>{i<steps.length-1&&<motion.div initial={{opacity:0,scale:.5}} animate={{opacity:1,scale:1}} transition={{delay:i*.18+.14}} className="grid h-8 w-8 shrink-0 place-items-center text-flow-violet"><ArrowDown className="h-5 w-5 md:-rotate-90"/></motion.div>}</div>)}</div></section>}
function RelationshipMap({object}:{object:EncounterActivity}){const nodes=object.content?.nodes||[];return <section className="mx-auto max-w-3xl"><h3 className="text-center text-[clamp(1.25rem,2.5vw,1.8rem)] font-black">{title(object)}</h3><div className="relative mt-8 grid gap-5 sm:grid-cols-2">{nodes.slice(0,6).map((node,i)=><motion.div key={node.id||i} initial={{opacity:0,scale:.86}} animate={{opacity:1,scale:1}} transition={{delay:i*.13}} className="relative flex min-h-24 items-center justify-center rounded-[2rem] border border-flow-violet/25 bg-flow-violet/[.08] p-5 text-center text-sm font-black"><span className="absolute -top-2 left-5 h-4 w-4 rounded-full bg-flow-orange"/>{normalizeReadableMath(node.label)}</motion.div>)}</div></section>}
function Comparison({object}:{object:EncounterActivity}){const columns=object.content?.columns||[],rows=object.content?.rows||[];return <section className="mx-auto max-w-3xl"><h3 className="text-center text-[clamp(1.25rem,2.5vw,1.8rem)] font-black">{title(object)}</h3><div className="relative mt-7 grid gap-3 sm:grid-cols-2"><span className="absolute left-1/2 top-1/2 z-10 hidden -translate-x-1/2 -translate-y-1/2 rounded-full bg-flow-void px-2 py-1 text-[10px] font-black text-flow-muted sm:block">VS</span>{columns.slice(0,2).map((column,i)=><motion.article key={column} initial={{opacity:0,x:i?24:-24}} animate={{opacity:1,x:0}} className={`rounded-3xl p-5 ${i?'bg-flow-violet/10':'bg-flow-orange/10'}`}><h4 className={`text-xl font-black ${i?'text-flow-violet':'text-flow-orange'}`}>{normalizeReadableMath(column)}</h4><ul className="mt-4 space-y-3 text-sm text-flow-muted">{rows.map((row,j)=>row[i]&&<li key={j} className="flex gap-2"><Check className="mt-1 h-4 w-4 shrink-0"/>{normalizeReadableMath(row[i])}</li>)}</ul></motion.article>)}</div></section>}
function Formula({object}:{object:EncounterActivity}){const [part,setPart]=useState(0),parts=object.content?.parts||[];return <section className="mx-auto max-w-3xl text-center"><h3 className="text-2xl font-black sm:text-3xl">{title(object)}</h3><div className="my-7 overflow-x-auto rounded-[2rem] bg-white/[.055] px-5 py-8 text-xl"><Copy>{`$$${object.content?.formula||object.content?.takeaway||''}$$`}</Copy></div>{parts.length>0&&<><p className="mx-auto max-w-lg rounded-2xl bg-flow-violet/10 p-4 text-sm"><strong className="mr-2 font-mono text-flow-violet">{parts[part].symbol}</strong>{parts[part].meaning}</p><button onClick={()=>setPart(v=>(v+1)%parts.length)} className="mt-3 min-h-11 text-sm font-black text-flow-orange">Highlight next part <ArrowRight className="inline h-4 w-4"/></button></>}</section>}
function Worked({object}:{object:EncounterActivity}){const [shown,setShown]=useState(1);const steps=Array.isArray(object.content?.steps)?object.content.steps.map((x:any,i)=>typeof x==='string'?{label:`Step ${i+1}`,body:x}:{label:x.label||`Step ${i+1}`,body:x.body}).filter(x=>x.body):[];if(!steps.length)return <Example object={object}/>;return <section className="mx-auto max-w-2xl"><h3 className="text-2xl font-black sm:text-3xl">{title(object)}</h3><ol className="mt-6 space-y-4">{steps.slice(0,shown).map((step,i)=><motion.li key={i} initial={{opacity:0,x:-16}} animate={{opacity:1,x:0}} className="grid grid-cols-[2.25rem_1fr] gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-flow-orange font-black text-flow-void">{i+1}</span><div><p className="font-black text-flow-violet">{step.label}</p><Copy>{step.body}</Copy></div></motion.li>)}</ol>{shown<steps.length&&<button onClick={()=>setShown(v=>v+1)} className="mt-6 min-h-12 rounded-full bg-flow-orange px-5 font-black text-flow-void">Show the next move</button>}</section>}
function Example({object}:{object:EncounterActivity}){return <section className="mx-auto max-w-2xl"><div className="flex items-center gap-3"><Sparkles className="text-flow-orange"/><h3 className="text-2xl font-black sm:text-3xl">{title(object)}</h3></div>{object.content?.lead&&<p className="mt-4 font-bold text-flow-violet">{normalizeReadableMath(object.content.lead)}</p>}<Copy className="mt-4">{object.content?.example||object.content?.body||object.content?.takeaway||object.prompt}</Copy></section>}
export function CollapsedPractice({activity}:{activity:EncounterActivity}){const [open,setOpen]=useState(false);return <section className="rounded-2xl bg-flow-success/[.06] px-4 py-2"><button onClick={()=>setOpen(v=>!v)} aria-expanded={open} className="flex min-h-11 w-full items-center gap-3 text-left"><Check className="h-4 w-4 text-flow-success"/><span className="flex-1 line-clamp-1 text-sm font-bold">{normalizeReadableMath(activity.prompt)}</span>{open?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{open&&<p className="pb-2 pl-7 text-xs text-flow-muted">Completed earlier. Your evidence is safely stored.</p>}</section>}
