'use client'
import { useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useSession } from 'next-auth/react'
import Link from 'next/link'
import { ArrowRight, CalendarDays, Clock3, RotateCcw, Sparkles } from 'lucide-react'
import { assignmentsApi, learningApi } from '@/lib/api'
import FlowCompanion from '@/components/onboarding/FlowCompanion'
import FlowLoader from '@/components/ui/FlowLoader'
import { normalizeReadableMath } from '@/lib/mathFormatting'
import { cn } from '@/lib/utils'

export default function HomePage() {
  const { data: auth } = useSession()
  const name = auth?.user?.name?.split(' ')[0] || 'there'
  const pathsQuery = useQuery({ queryKey: ['learning-paths'], queryFn: () => learningApi.getPaths().then(r => Array.isArray(r.data) ? r.data : r.data?.results || []) })
  const paths = useMemo(() => pathsQuery.data || [], [pathsQuery.data])
  const active = useMemo(() => paths.find((path: any) => path.status === 'active') || paths.find((path: any) => path.status !== 'completed'), [paths])
  const otherSpaces = paths.filter((path: any) => path.id !== active?.id && path.status !== 'completed').slice(0, 3)
  const pathQuery = useQuery({ queryKey: ['learning-path', active?.id], queryFn: () => learningApi.getPath(active.id).then(r => r.data), enabled: Boolean(active?.id) })
  const concepts = pathQuery.data?.concepts || []
  const current = concepts.find((concept: any) => concept.status === 'current')
  const lastCompleted = [...concepts].filter((concept: any) => concept.status === 'completed').sort((a: any, b: any) => b.order_index - a.order_index)[0]
  const teachingQuery = useQuery({ queryKey: ['teaching-session', current?.id], queryFn: () => learningApi.getTeachingSession(current.id).then(r => r.data), enabled: Boolean(current?.id), retry: false })
  const assignmentsQuery = useQuery({ queryKey: ['assignments'], queryFn: () => assignmentsApi.getAll().then(r => Array.isArray(r.data) ? r.data : r.data?.results || []), retry: false })
  const due = paths.reduce((total: number, path: any) => total + Number(path.due_reviews || 0), 0)
  const upcoming = [...(assignmentsQuery.data || [])].filter((item: any) => {
    const value = item.due_date || item.deadline_date || item.deadline
    return value && +new Date(value) >= Date.now() - 86_400_000
  }).sort((a: any, b: any) => +new Date(a.due_date || a.deadline_date || a.deadline) - +new Date(b.due_date || b.deadline_date || b.deadline))[0]
  const openSession = teachingQuery.data && !['completed', 'not_started'].includes(teachingQuery.data.status)
  const primaryHref = current ? `/learn/${active?.id}?concept=${current.id}` : `/learn/${active?.id}`
  const conceptTitle = normalizeReadableMath(current?.title || active?.title || 'Continue your Journey')
  const conceptDescription = cleanSummary(current?.summary || current?.description || active?.description || active?.goal)

  if (pathsQuery.isLoading) return <FlowLoader state="thinking" message="Checking where we left off." className="min-h-[80dvh]" />
  if (pathsQuery.isError) return <main className="flow-atmosphere grid min-h-[70dvh] place-items-center px-5 text-center"><div><FlowCompanion state="encouraging" className="mx-auto w-28" /><h1 className="mt-4 text-3xl font-black">Your place is saved.</h1><p className="mt-2 text-flow-muted">Flow couldn’t reach it just now.</p><button onClick={() => pathsQuery.refetch()} className="flow-primary-button mt-6">Try again</button></div></main>
  if (!active) return <EmptyHome />

  return <main className="flow-atmosphere min-h-[calc(100dvh-4rem)] overflow-x-hidden px-4 pb-24 pt-6 min-[390px]:px-5 sm:py-9 md:px-10 lg:px-14"><div className="mx-auto max-w-[86rem]">
    <header><p className="flow-eyebrow">Welcome back, {name}</p><h1 className="mt-2 max-w-3xl text-[clamp(2.15rem,5vw,3.75rem)] font-black leading-[.98] tracking-[-.05em]">{openSession ? 'Pick up the thread.' : 'Your next move is ready.'}</h1></header>

    <div className="mt-6 grid gap-4 sm:mt-8 lg:grid-cols-[minmax(0,1fr)_19rem] xl:grid-cols-[minmax(0,1fr)_21rem]">
      <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-surface-container p-5 shadow-[0_22px_70px_rgba(0,0,0,.22)] sm:p-7 lg:p-8"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_88%_12%,rgba(255,122,26,.14),transparent_22rem)]" /><div className="relative">
        <div className="flex flex-wrap items-center justify-between gap-3"><p className="flow-eyebrow">{openSession ? 'Continue learning' : 'Up next'}</p><span className="rounded-full bg-white/[.06] px-3 py-1 text-xs font-black text-flow-muted">{active.mastery_percent || 0}% Journey</span></div>
        <p className="mt-5 text-xs font-black uppercase tracking-[.16em] text-flow-muted">{active.subject || active.title}</p>
        <h2 className="mt-2 max-w-4xl break-words text-[clamp(1.75rem,4vw,2.75rem)] font-black leading-[1.04] tracking-[-.04em]">{conceptTitle}</h2>
        {conceptDescription && <p className="mt-3 max-w-2xl text-sm leading-relaxed text-flow-muted sm:text-base">{conceptDescription}</p>}
        <div className="mt-5 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm font-bold text-flow-muted">{current && <span className="inline-flex items-center gap-2"><Clock3 className="h-4 w-4 text-flow-orange" />{current.estimated_minutes || 15} min</span>}{current && <span>25 XP</span>}{openSession && <span className="text-flow-success">{teachingQuery.data.completion_evaluation?.objectives_satisfied || 0}/{teachingQuery.data.completion_evaluation?.objectives_total || teachingQuery.data.objectives?.length || 0} objectives understood</span>}</div>
        <div className="mt-6 h-1.5 max-w-2xl overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-flow-success to-flow-orange transition-[width] duration-500 motion-reduce:transition-none" style={{ width: `${active.mastery_percent || 0}%` }} /></div>
        <Link href={primaryHref} className="flow-primary-button mt-7 w-full rounded-xl sm:w-auto">Continue with Flow <ArrowRight className="h-5 w-5" /></Link>
      </div></section>

      <aside className="flex items-center gap-4 rounded-3xl border border-flow-violet/20 bg-flow-violet/[.07] p-4 sm:p-5 lg:block"><FlowCompanion state={openSession ? 'teaching' : due ? 'encouraging' : 'idle'} className="w-20 shrink-0 sm:w-24 lg:mx-auto lg:w-32" /><div className="min-w-0 lg:mt-4 lg:text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-flow-violet">Flow</p><p className="mt-2 text-sm font-bold leading-relaxed text-flow-ink">{flowContext({ openSession, lastCompleted, current, due })}</p></div></aside>
    </div>

    <section className="mt-5 rounded-2xl border border-white/[.08] bg-surface-container-low p-4 sm:flex sm:items-center sm:justify-between sm:gap-5 sm:p-5"><div className="flex min-w-0 items-start gap-3"><Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-flow-violet" /><div><p className="text-xs font-black uppercase tracking-[.16em] text-flow-violet">Flow suggests</p><h2 className="mt-1 text-base font-black sm:text-lg">{due ? `Warm up with ${due === 1 ? 'the review that is' : `${due} reviews that are`} due.` : upcoming ? `Keep ${upcoming.title || upcoming.name || 'your assignment'} on your radar.` : `Ask Flow one question about ${conceptTitle}.`}</h2></div></div><Link href={due ? `/learn/${active.id}` : upcoming ? '/assignments' : `/ai?journey=${active.id}${current ? `&concept=${current.id}` : ''}`} className="mt-4 inline-flex min-h-11 shrink-0 items-center gap-1 rounded-xl px-3 text-sm font-black text-flow-violet transition hover:bg-flow-violet/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-violet sm:mt-0">{due ? 'Start review' : upcoming ? 'See assignment' : 'Ask Flow'} <ArrowRight className="h-4 w-4" /></Link></section>

    <section className="mt-10 sm:mt-12"><div className="flex items-end justify-between gap-4"><div><p className="flow-eyebrow">Your learning spaces</p><h2 className="mt-2 text-2xl font-black tracking-[-.03em] sm:text-3xl">Jump back in.</h2></div><Link href="/learn" className="shrink-0 text-sm font-black text-flow-violet focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-violet">All Journeys →</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[active, ...otherSpaces].map((space: any) => <LearningSpace key={space.id} space={space} active={space.id === active.id} nextConcept={space.id === active.id ? current : undefined} />)}</div></section>

    {(upcoming || due > 0) && <section className="mt-10 border-t border-white/[.08] pt-7"><p className="flow-eyebrow">Today</p><div className="mt-4 grid gap-3 md:grid-cols-2">{due > 0 && <TodayItem icon={<RotateCcw className="h-5 w-5" />} label="Review opportunity" title={`${due} ${due === 1 ? 'concept is' : 'concepts are'} ready to revisit`} href={`/learn/${active.id}`} />}{upcoming && <TodayItem icon={<CalendarDays className="h-5 w-5" />} label={formatDeadline(upcoming.due_date || upcoming.deadline_date || upcoming.deadline)} title={upcoming.title || upcoming.name || 'Upcoming assignment'} href="/assignments" />}</div></section>}
  </div></main>
}

function LearningSpace({ space, active, nextConcept }: { space: any; active: boolean; nextConcept?: any }) { const progress = Number(space.mastery_percent || 0); return <Link href={`/learn/${space.id}`} className={cn('group flex min-h-44 flex-col rounded-2xl border p-5 transition duration-200 motion-reduce:transition-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-orange', active ? 'border-flow-orange/40 bg-surface-active shadow-[0_14px_35px_rgba(0,0,0,.18)]' : 'border-white/[.08] bg-surface-container-low hover:-translate-y-0.5 hover:border-flow-violet/30 hover:bg-surface-hover motion-reduce:hover:translate-y-0')}><div className="flex items-center justify-between gap-3"><span className={cn('text-[.65rem] font-black uppercase tracking-[.16em]', active ? 'text-flow-orange' : 'text-flow-muted')}>{active ? 'Current Journey' : space.status || 'Journey'}</span><span className="text-xs font-black text-flow-muted">{progress}%</span></div><h3 className="mt-3 line-clamp-2 break-words text-xl font-black leading-tight">{space.subject || space.title}</h3><p className="mt-2 line-clamp-2 text-sm text-flow-muted">{nextConcept ? `Next: ${normalizeReadableMath(nextConcept.title)}` : space.goal || `${space.concepts_completed || 0} of ${space.total_concepts || 0} concepts complete`}</p><div className="mt-auto pt-5"><div className="h-1 overflow-hidden rounded-full bg-white/10"><div className={cn('h-full rounded-full transition-[width] duration-500 motion-reduce:transition-none', active ? 'bg-flow-orange' : 'bg-flow-violet')} style={{ width: `${progress}%` }} /></div><span className="mt-3 inline-flex items-center gap-1 text-sm font-black text-flow-ink">{active ? 'Continue' : 'Open'} <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5 motion-reduce:transition-none" /></span></div></Link> }
function TodayItem({ icon, label, title, href }: { icon: React.ReactNode; label: string; title: string; href: string }) { return <Link href={href} className="group flex items-center gap-4 rounded-2xl border border-white/[.08] bg-surface-container-low p-4 transition hover:bg-surface-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-violet"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-flow-violet/10 text-flow-violet">{icon}</span><span className="min-w-0"><span className="block text-xs font-black uppercase tracking-[.14em] text-flow-muted">{label}</span><span className="mt-1 block truncate font-black">{title}</span></span><ArrowRight className="ml-auto h-4 w-4 shrink-0 text-flow-muted transition group-hover:translate-x-0.5" /></Link> }
function EmptyHome() { return <main className="flow-atmosphere min-h-[calc(100dvh-4rem)] px-5 pb-24 pt-8 md:px-12"><div className="mx-auto grid max-w-6xl items-center gap-8 lg:grid-cols-[minmax(0,1fr)_16rem]"><section><p className="flow-eyebrow">Your first move</p><h1 className="mt-3 max-w-3xl text-[clamp(2.35rem,6vw,4rem)] font-black leading-[.98] tracking-[-.05em]">Bring the material.<br /><span className="text-flow-orange">I’ll find the route.</span></h1><p className="mt-5 max-w-xl text-base text-flow-muted sm:text-lg">Give Flow something you’re learning and it will become your first grounded Journey.</p><div className="mt-7 grid gap-3 sm:flex"><Link href="/learn?create=1" className="flow-primary-button rounded-xl">Create a Journey <ArrowRight /></Link><Link href="/library" className="inline-flex min-h-12 items-center justify-center rounded-xl px-4 font-black text-flow-violet focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-flow-violet">Choose from Sources</Link></div></section><FlowCompanion state="encouraging" className="mx-auto w-32 sm:w-40 lg:w-52" /></div></main> }
function cleanSummary(value?: string) { if (!value) return ''; const oneLine = value.replace(/\s+/g, ' ').trim(); return oneLine.length > 180 ? `${oneLine.slice(0, 177).trimEnd()}…` : oneLine }
function flowContext({ openSession, lastCompleted, current, due }: { openSession: any; lastCompleted: any; current: any; due: number }) { if (openSession && current) return `We were working through ${normalizeReadableMath(current.title)}. Your progress is still right where you left it.`; if (lastCompleted && current) return `Last time, you finished ${normalizeReadableMath(lastCompleted.title)}. Next, we’re tackling ${normalizeReadableMath(current.title)}.`; if (current && due) return `${due === 1 ? 'One earlier idea needs' : `${due} earlier ideas need`} a quick refresh before ${normalizeReadableMath(current.title)}.`; if (current) return `Next, we’re tackling ${normalizeReadableMath(current.title)}.`; return 'This Journey is complete. Pick another space whenever you’re ready.' }
function formatDeadline(value: string) { const date = new Date(value); const tomorrow = new Date(); tomorrow.setDate(tomorrow.getDate() + 1); return date.toDateString() === tomorrow.toDateString() ? 'Due tomorrow' : `Due ${date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}` }
