# Generated by Django 5.2.17 on 2026-08-24 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowCoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flowcoin_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('streak_shields', models.PositiveSmallIntegerField(default=0)),
                ('last_qualifying_activity_date', models.DateField(blank=True, null=True)),
                ('migrated', models.BooleanField(default=False, help_text='True after existing XP/streak data has been migrated from legacy fields.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-lifetime_xp'],
            },
        ),
        migrations.CreateModel(
            name='FlowCoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for earned, negative for spent.')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('migration_bonus', 'Migration Bonus')], max_length=30)),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_id', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('balance_after', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Prevents duplicate FlowCoin awards.', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gamification.flowcoinwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'transaction_type'], name='gamificatio_wallet__e89c6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreakActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('activity_type', models.CharField(choices=[('study_session', 'Study Session'), ('flashcard_session', 'Flashcard Session'), ('quiz_completion', 'Quiz Completion'), ('concept_completion', 'Concept Completion'), ('exam_prep_completion', 'Exam Prep Completion'), ('battle_win', 'Battle Win')], max_length=40)),
                ('source_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='gamificatio_user_id_dbbc8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for XP earned, negative for XP spent (marketplace).')),
                ('source_type', models.CharField(choices=[('study_step', 'Study Step'), ('quiz_completion', 'Quiz Completion'), ('flashcard_session', 'Flashcard Session'), ('concept_completion', 'Concept Completion'), ('battle_participation', 'Battle Participation'), ('battle_win', 'Battle Win'), ('battle_perfect', 'Battle Perfect Score'), ('assignment_completion', 'Assignment Completion'), ('exam_prep_completion', 'Exam Prep Completion'), ('feedback', 'Feedback'), ('study_time', 'Study Time'), ('xp_pack_purchase', 'XP Pack Purchase'), ('marketplace_spend', 'Marketplace Spend'), ('migration', 'Migration'), ('admin_adjustment', 'Admin Adjustment')], max_length=40)),
                ('source_id', models.CharField(blank=True, default='', help_text='Object ID that triggered this transaction (e.g. resource ID, battle ID).', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Prevents duplicate rewards for the same event.', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'source_type'], name='gamificatio_user_id_b73f3c_idx')],
            },
        ),
    ]
