export interface ThemeConfig {
  name: string
  vars: Record<string, string>
}

export const THEME_CONFIGS: Record<string, ThemeConfig> = {
  'default': {
    name: 'Midnight Ember',
    vars: {
      '--background': '#121416',
      '--surface-container-low': '#1a1c1e',
      '--surface-container': '#1e2022',
      '--surface-container-high': '#282a2c',
      '--primary': '#ffb68d',
      '--primary-container': '#ff8a3d',
      '--on-primary': '#532200',
      '--on-primary-fixed-variant': '#763300',
      '--secondary': '#bfc2ff',
      '--tertiary': '#d4bbff',
      '--outline-variant': '#564338',
      '--on-surface': '#e2e2e5',
      '--on-surface-variant': '#ddc1b3',
    },
  },
  'light': {
    name: 'Daylight',
    vars: {
      '--background': '#faf8f5',
      '--surface-container-low': '#f0ede8',
      '--surface-container': '#e8e5e0',
      '--surface-container-high': '#ddd9d3',
      '--primary': '#d4723a',
      '--primary-container': '#ff8a3d',
      '--on-primary': '#ffffff',
      '--on-primary-fixed-variant': '#532200',
      '--secondary': '#4a4dc7',
      '--tertiary': '#8a5dc7',
      '--outline-variant': '#c8c3bc',
      '--on-surface': '#1c1b1f',
      '--on-surface-variant': '#49454f',
    },
  },
  'theme_emerald': {
    name: 'Forest Emerald',
    vars: {
      '--background': '#0a1a14',
      '--surface-container-low': '#0f2a1f',
      '--surface-container': '#132e23',
      '--surface-container-high': '#1a3d2e',
      '--primary': '#34d399',
      '--primary-container': '#10b981',
      '--on-primary': '#022c22',
      '--on-primary-fixed-variant': '#064e3b',
      '--secondary': '#a7f3d0',
      '--tertiary': '#6ee7b7',
      '--outline-variant': '#065f46',
      '--on-surface': '#ecfdf5',
      '--on-surface-variant': '#a7f3d0',
    },
  },
  'theme_amethyst': {
    name: 'Royal Amethyst',
    vars: {
      '--background': '#130d21',
      '--surface-container-low': '#1e1433',
      '--surface-container': '#24183d',
      '--surface-container-high': '#31204f',
      '--primary': '#a78bfa',
      '--primary-container': '#8b5cf6',
      '--on-primary': '#1e1042',
      '--on-primary-fixed-variant': '#2e1065',
      '--secondary': '#ddd6fe',
      '--tertiary': '#c4b5fd',
      '--outline-variant': '#4c1d95',
      '--on-surface': '#ede9fe',
      '--on-surface-variant': '#ddd6fe',
    },
  },
  'theme_nordic': {
    name: 'Nordic Slate',
    vars: {
      '--background': '#0c1220',
      '--surface-container-low': '#121a2d',
      '--surface-container': '#162036',
      '--surface-container-high': '#1e2d45',
      '--primary': '#94a3b8',
      '--primary-container': '#64748b',
      '--on-primary': '#0f172a',
      '--on-primary-fixed-variant': '#1e293b',
      '--secondary': '#cbd5e1',
      '--tertiary': '#94a3b8',
      '--outline-variant': '#334155',
      '--on-surface': '#f1f5f9',
      '--on-surface-variant': '#cbd5e1',
    },
  },
  'theme_neon': {
    name: 'Cyberpunk Neon',
    vars: {
      '--background': '#05050a',
      '--surface-container-low': '#0a0a14',
      '--surface-container': '#0f0f1a',
      '--surface-container-high': '#1a1a28',
      '--primary': '#f472b6',
      '--primary-container': '#ec4899',
      '--on-primary': '#1a0012',
      '--on-primary-fixed-variant': '#3b0026',
      '--secondary': '#22d3ee',
      '--tertiary': '#a855f7',
      '--outline-variant': '#521a3d',
      '--on-surface': '#fdf2f8',
      '--on-surface-variant': '#f9a8d4',
    },
  },
}
