# Generated by Django 5.2.16 on 2026-07-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_total_resources_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='app_name',
            field=models.CharField(default='Flow State', max_length=100),
        ),
    ]
