# Generated by Django 6.0.3 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_globalconfig_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('tertiary', 'Tertiary / University'), ('secondary', 'Secondary / Senior High School (Ghana)')], default='tertiary', max_length=20),
        ),
    ]
